[package]
name = "lapimposteur"
version = "0.1.0"
authors = ["Cyril Delmas <c.delmas@lectra.com>"]

[[bin]]
name = "lapimposteur"

[dependencies]
clap = "2.32.0"
config = { version = "0.9", features = ["hjson"] }
env_logger = "0.5.13"
lapimposteur-lib = { version = "^0.1.0", path = "../lib" }
log = "0.4.6"
